### ISSUE TITLE
Orchard 1.10

### ISSUE THREAD

**Issue by hsimah** [Lombiq/Orchard-Avatars#2]
Hi guys, I've upgraded my site to 1.10 and have made the necessary updates locally to this module. I can't seem to create a pull request (getting access denied). I'm new to contributing to Orchard so not sure if I'm doing it correctly.

**Comment by Piedone** [comment]
Thank you, that sounds great! What did you try exactly? Because there should be nothing preventing you from submitting a pull request to this repository. Maybe this tutorial on PRs can help you: https://help.github.com/articles/using-pull-requests/

**Comment by hsimah** [comment]
That was helpful. I hadn't forked the repo. Thanks.
